apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: bank-namespace
data:
  nginx.conf: |
    worker_processes auto;
    pid /tmp/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        server {
            listen 8080 default_server;
            server_name "";
            add_header Content-Type text/plain;
            return 200 'Awesome!';
        }
        
        server {
            listen 8080;
            server_name
                *.lion.nyhhs.com
                *.elb.ap-northeast-3.amazonaws.com
                *.ap-northeast-3.elb.amazonaws.com
                *.awsglobalaccelerator.com;

            location / {
                proxy_pass http://frontend-server:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /api {
                proxy_pass http://backend-server:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
