apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
  namespace: bank-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: frontend
        image: nexus.mycluster.shop:5000/node-frontend:v0.0.1
        imagePullPolicy: IfNotPresent # IfNotPresent or Always
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: JWT_SECRET
          value: "thisIsMySecretKey"
        - name: BACKEND_HOST
          value: "backend-server"
        - name: BACKEND_PORT
          value: "8000"
        - name: CLIENT_ID
          value: "CLIENT_ID"
        - name: CLIENT_SECRET
          value: "CLIENT_SECRET"
        - name: REDIRECT_URI
          value: "https://10.123.123.30/naverlogin/login"
        - name: JAVASCRIPT_APPKEY
          value: "8c5d619d1031b451f450fa5338eff279"
        - name: REDIS_HOST
          value: "redis-server"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_SECRET
          value: "20240930ProjectSecretKey"
        - name: AWS_ACCESS_KEY_ID
          value: "AWS_ACCESS_KEY_ID"
        - name: AWS_SECRET_ACCESS_KEY
          value: "AWS_SECRET_ACCESS_KEY"
        - name: AWS_DEFAULT_REGION
          value: "ap-northeast-3"
        - name: SERVER_TYPE
          value: "3"
        ports:
        - containerPort: 3000
