apiVersion: v1
kind: Service
metadata:
  name: backend-server
  namespace: bank-namespace
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30800
  selector:
    app: backend
