apiVersion: v1
kind: Service
metadata:
  name: frontend-server
  namespace: bank-namespace
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30300
  selector:
    app: frontend
